# version: "3"

# services:

#   posts-svc:
#     build:
#       context: "./microservices/posts"
#     networks:
#       - "posts-svc"
#     ports:
#       - "50051:50051"
#     depends_on:
#       - "posts-db"
#       - "cache"
#     environment:
#       DATABASE_URL: "mongodb://saaf95:saaf95@localhost:27017/postsdb?authSource=admin&directConnection=true"
#     restart: "on-failure"

#   posts-db:
#     image: prismagraphql/mongo-single-replica:5.0.3
#     container_name: "posts-db"
#     ports:
#       - 27017:27017
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: saaf95
#       MONGO_INITDB_ROOT_PASSWORD: saaf95
#     restart: "on-failure"

#   cache:
#     image: "redis:5-alpine"
#     container_name: "redis-cache"
#     networks:
#       - "frontend"
#       - "backend"
#     expose:
#       - "6379"
#     healthcheck:
#       test: ["CMD-SHELL", "sh -c 'redis-cli PING'"]
#       interval: 30s
#       timeout: 30s
#       retries: 3
#     restart: "on-failure"

# networks:
#   posts-svc:

version: '3.7'

services:
  # posts:
  #   container_name: myklad-posts-svc
  #   build:
  #     context: .
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 9229:9229
  #   command: npm run start:dev
  #   env_file:
  #     - .env
  #   networks:
  #     - webnet
  #   depends_on:
  #     - redis
  #     - posts-db

  # redis:
  #   image: redis:5
  #   container_name: myklad-redis
  #   networks:
  #     - webnet

  posts-db:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: "myklad-posts-db"
    networks:
      - webnet
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: saaf95
      MONGO_INITDB_ROOT_PASSWORD: saaf95
    restart: "on-failure"
    volumes:
      - mongodata:/var/lib/mongodb/data
  socialdb:
    image: neo4j:4.4.12-community
    container_name: mk_neo4j_container
    restart: unless-stopped
    ports:
      - '7474:7474' # browser access
      - '7687:7687' # browser access
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_default__database=myklad
    volumes:
      - gdb:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  webnet:
volumes:
  mongodata:
  gdb:
    driver: local